### ISSUE TITLE
Specific addon install instructions for newbies

### ISSUE THREAD

**Issue by akshu1111** [GraphicArtQuest/Blender-Scripting-Assistant#8]
### Component

README

### Description

To install this addon, I renamed the **src** folder to "blender-scripting-assistant" and the name was important.
Then I zipped it to the same name .zip
Then I did Blender>Edit>Preferences>Addons>Install> browse out the zip.

Changing names would give an error later since the plugin tries to find itself by original name: 
`KeyError: 'bpy_prop_collection[key]: key "blender-scripting-assistant" not found'`

Also, sometimes on pressing the Start Server button, it may seems it doesnt work since the script gets paused. Opening the "Toggle terminal" and pressing Enter/Return in it will resume the script.

### Are you able/willing to make the change? (It's ok if you're not!)

No

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/GraphicArtQuest/Blender-Scripting-Assistant/blob/master/CODE_OF_CONDUCT.md)

**Comment by M-Scott-Lassiter** [comment]
Thanks for the feedback! I read over your issue, and what I understand is to install this you:

1) Copied the source folder onto your computer
2) Renamed this folder to "blender-scripting-assistant"
3) Zipped the folder to "blender-scripting-assistant.zip"

Is that correct?

If so, I believe you are absolutely right that I need to update the docs, and for that matter, it looks like I need to get the final distribution file up as a release! If you run the [build.py](https://github.com/GraphicArtQuest/Blender-Scripting-Assistant/blob/main/build.py) script, it will automatically bundle the source files and put them in a `dist` folder in a zip file.

Can you confirm for me that I have understood your problem accurately before I make that update?

**Comment by akshu1111** [comment]
Yes I understand that. Also, I had to create the dist directory or else it just doesnt create by itself.  Coders wont have any issue ofcourse.
